instances:
  - id: demo
    adapter:
      type: pajgps
      endpoint: https://connect.paj-gps.com/api/v1
      username: username
      password: password
      interval: 10
      autologoff: 1800
    broker:
      host: mqtt.yourdomain.com
      port: 1883
      username: username
      password: password
    vdv435:
      organisation: demo
      itcs: 1